version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # or 16 depending on your project
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: .next
